src/Nixfmt/Predoc.hs, src/Nixfmt/Pretty.hs
Please see individual commit messages for the issues they fix.
Fixes #17 
Fixes #18 
Fixes #19
=> Fix multiple small formatting issues

js/index.html
- Fixes layout in chrome
- fixes race condition on load
=> js: attempt to fix issues

shell.nix, src/Nixfmt/Predoc.hs, src/Nixfmt/Pretty.hs
This should solve the main issue with indentation. There are still many edge cases that need to be addressed one by one, but most code should now get formatted nicely.
The first four commits are just refactoring and should not have semantic changes. The final commit is what solves the indentation issue.
=> [INT-82] Format expressions

nixpkgs.nix, release.nix
=> Repin nixpkgs

main/Main.hs
=> Add check and quiet flags

src/Nixfmt/Parser.hs, src/Nixfmt/Pretty.hs
=> Fix some expressions that changed semantics when formatted

main/Main.hs, nixfmt.cabal
=> Include version in `--version` output

src/Nixfmt/Pretty.hs
=> Fix indentation of leading comments in parens

.buildkite/pipeline.yml
Version control is good. Steps copied verbatim from the buildkite settings
=> Store buildkite pipeline steps in the repository

.buildkite/pipeline.yml, .reuse/dep5, flake.nix
=> Add reuse lint step

CHANGELOG.md, flake.lock, nixfmt.cabal
Prepare for 0.5.0 release. After merging:
=> Update changelog, bump version to 0.5.0

js/index.html
Also enforced correct viewport scaling.
Galaxy Note 20, before and after
=> nixfmt.github.io: impl layout in flexbox

CHANGELOG.md, main/Main.hs
=> Fix nixfmt trying to allocate temp files that aren't used

flake.nix
=> flake: convert (devShell, defaultPackage, defaultApp) to new style

src/Nixfmt/Parser/Float.hs
=> float's can't start with just exponents

README.md
1) Remove cachix cache mentions since it's no longer used.
2) Update build status badge
=> [Chore] Minor README updates

README.md
Part of https://github.com/serokell/nixfmt/issues/153
=> readme: Add status note

.github/workflows/main.yml
https://github.com/tomberek/nixfmt/actions/runs/8412676563/job/23033814428#step:6:1334
Fixes: https://github.com/NixOS/nixfmt/issues/165
=> ci: run tests

main/Main.hs, nixfmt.cabal, src/Nixfmt.hs
Very useful for debugging!
```haskell
❯ cabal run nixfmt -- --ast <<< "1 + 1"
Operation
( Term
( Token
( Ann []
( Integer 1 ) Nothing
)
)
)
( Ann [] TPlus Nothing )
( Term
( Token
( Ann []
( Integer 1 ) Nothing
)
)
)
```
=> Add an AST pretty-printing mode

nixfmt.cabal
https://github.com/NixOS/nixpkgs/pull/324192#discussion_r1663384565
The synopsis now matches the repo description
=> Update synopsis and description

scripts/sync-pr.sh
a78b63e03b69306ff54346fce554250823f5377e made it do a merge commit, but that requires an identity to be set: https://github.com/NixOS/nixfmt/actions/runs/10610964217/job/29409472985?pr=243
Ping @dasJ
=> Fix Nixpkgs diff

src/Nixfmt/Pretty.hs, test/diff/idioms_nixos_2/out-pure.nix, test/diff/idioms_nixos_2/out.nix
=> Improve line wrapping and width handling

main/Main.hs, test/mergetool.sh
Turns out there are some problems to fix, see the commit messages for details. I made sure to add regression tests.
---
This work is funded by [Antithesis](https://antithesis.com/) and [Tweag](https://tweag.io) :sparkles:
=> Mergetool fixes
