NixOS/nixfmt

- src/Nixfmt/Parser.hs
- src/Nixfmt/Pretty.hs
- src/Nixfmt/Types.hs
I've removed the special case of moving comments past commas for now.
I've indented comments that get moved before the in keyword for now,
that can be fixed after leading comments are actually stored with the
token they lead, rather than the previous token.
Fixes #23
> Make nixfmt omnipotent^W idempotent

- src/Nixfmt/Pretty.hs
Fixes #31. Handling of set abstractions can still be improved by quite a bit, but it would be messy until #32 is fixed.
> Quick fix for commas not having spacing

- src/Nixfmt/Predoc.hs
- src/Nixfmt/Pretty.hs
Fixes #34
See https://github.com/serokell/nixpkgs/tree/formatted for the results.
> Indent parenthesized and with and assert expressions

- main/Main.hs
This changes the reporting of non-conforming files when using the `--check` option from the format
filename.nix:
not formatted
to
filename.nix: not formatted
to better suit line oriented tools like `sed` or `grep`.
Fixes #49
> Print "not formatted" check result on one line

- .buildkite/pipeline.yml
- default.nix
- js/404.html
Analagous to ghc.dev setup: https://github.com/serokell/ghc.dev/blob/master/.buildkite/pipeline.yml
The pipeline needs proper AWS credentials to make it work
> [OPS-934] Deploy website to AWS, add 404 page

- .buildkite/pipeline.yml
`aws s3 sync` compares file sizes and timestamps to decide if a file in
the bucket needs to be replaced, but all files in nix store have
timestamp=1. So if a new file happens to have the same size as the old
one, `aws s3 sync` would decide that it does not need to be updated.
Copy files to the local directory updating their timestamps to the
current time to fix it
> [OPS-984] Deployment: run `aws cp` before `aws sync` to replace existing files

- src/Nixfmt/Parser.hs
- src/Nixfmt/Pretty.hs
- src/Nixfmt/Util.hs
> Correctly handle last lines with spaces

- .buildkite/pipeline.yml
Buildkite was giving a passing status on broken nixfmt-webdemo builds. Try to fix this using pipefail.
> Add pipefail on nixfmt-webdemo

- main/Main.hs
This PR adds the default number of maximum character width in the usage of the cli. Running
```bash
nixfmt --help
```
now prints
```
nixfmt v0.5.0
nixfmt [OPTIONS] [FILES]
Format Nix source code
Common flags:
-w --width=INT        Maximum width in characters
[default: 80]
-c --check            Check whether files are formatted
-q --quiet            Do not report errors
-v --verify           Check that the output parses and formats the same as
the input
-? --help             Display help message
-V --version          Print version information
--numeric-version  Print just the version number
```
> Add default width length info in cli help

- CHANGELOG.md
- main/Main.hs
Fixes #99 
https://github.com/NixOS/nix/blob/master/src/nix/fmt.cc#L42
> nixfmt cmd: support recursively formatting an entire directory (nix fmt compat)

- CHANGELOG.md
- nixfmt.cabal
- src/Nixfmt/Parser.hs
- src/Nixfmt/Parser/Float.hs
Fixes #98, #86, #85
I'm very unhappy over having to copy this much code from megaparsec, but it doesn't export it. See https://hackage.haskell.org/package/megaparsec-9.2.2/docs/src/Text.Megaparsec.Char.Lexer.html#float
Not sure about the version bounds on scientific.
> floats: allow starting with ., prefer over int (nix compat)

- .buildkite/pipeline.yml
Problem: This repo still uses the old 'nix run' command format for which we still keep a workaround in CI agent configuration.
Solution: Update CI steps to use new nix commands.
> [Chore] Update CI to use new nix commands

- team/README.md
Adds very basic team documentation as outlined in https://github.com/serokell/nixfmt/issues/153
Please review @piegamesde, @Sereja313, @dasJ, @0x4A6F, @tomberek
> Create team document

- .github/workflows/main.yml
The web demo will be retired from this repo soon anyways, see https://github.com/NixOS/nixfmt/issues/157
I believe it also relied on using Serokell's self-hosted action runners, which we can't use anymore now that the repo has been transferred, so we use the default ubuntu-latest instead.
> ci: remove deploy and fix after repo transfer

- standard.md
Imports the initial standard formatting from https://github.com/NixOS/rfcs/blob/5d5eef7078284e5632d4eb11a06517681fff9aaf/rfcs/0166-nix-formatting.md#terms-and-definitions
> import initial standard formatting

- .github/workflows/main.yml
- default.nix
- flake.nix
Various improvements to the Nix code:
- Use the new [`lib.fileset`](https://nixos.org/manual/nixpkgs/unstable/#sec-functions-library-fileset) library instead of `builtins.path` and regex based source filtering
- Fix https://github.com/NixOS/nixfmt/issues/143 by always using `justStaticExecutables` (doesn't mean the binaries are statically linked confusingly)
- Don't build the haddocks anymore, we won't need those anyways with https://github.com/NixOS/nixfmt/issues/161
- Remove `nixfmt-deriver`, doesn't seem necessary
- Switch to `haskellPackages.shellFor`, a bit cleaner
- Add [haskell-language-server](https://github.com/haskell/haskell-language-server) to the environment, makes development very nice!
> Nix improvements

- team/README.md
Now that https://github.com/NixOS/nixos-homepage/pull/1337 is merged
> Add link to nixos.org page

- .reuse/dep5
- CHANGELOG.md
- CONTRIBUTING.md
- MAINTENANCE.md
- README.md
- default.nix
- flake.nix
- main/Main.hs
- main/System/IO/Atomic.hs
- main/System/IO/Utf8.hs
- nixfmt.cabal
- shell.nix
- src/Nixfmt.hs
- src/Nixfmt/Lexer.hs
- src/Nixfmt/Parser.hs
- src/Nixfmt/Parser/Float.hs
- src/Nixfmt/Predoc.hs
- src/Nixfmt/Pretty.hs
- src/Nixfmt/Types.hs
- src/Nixfmt/Util.hs
- standard.md
- team/README.md
- test/README.md
- test/test.sh
As discussed in https://github.com/NixOS/nixfmt/issues/164, we want to avoid requiring copyright notices in each file and instead condense them into a single place.
All copyright holders agreed to doing this already, but it would still be good to get an approval on this PR.
Note that I didn't remove REUSE 3.0, but just kind of cheated by using `*` to set the copyright for all files (I hope that works, we'll see when CI runs..) :)
Ping @Sereja313 @gromakovsky @piegamesde @Lucus16
> Condense REUSE 3.0 copyright and license notes

- .reuse/dep5
As discussed in https://github.com/NixOS/nixfmt/issues/169
While this does change the copyright notice, which is technically not allowed by MPL-2.0 https://github.com/NixOS/nixfmt/blob/b84dba1c7b4c3eff2faf8cbc47381a2ad2be5734/LICENSE#L198-L204
I believe it should be fine if we can get all of the individuals approval. @Lucus16 already indicated approval in https://github.com/NixOS/nixfmt/issues/169#issuecomment-2008122683:
> In my case I don't mind you removing my copyright notices
I'm also fine with my name being removed.
We only need @piegamesde's explicit approval now.
Note that this doesn't remove the copyright of the contributions, it just changes the copyright note.
CC @Sereja313 @gromakovsky
> Remove individuals from copyright in favor of "nixfmt contributors"

- .github/workflows/main.yml
- .gitignore
- .stylish-haskell.yaml
- CONTRIBUTING.md
- README.md
- nixfmt.cabal
- src/Nixfmt.hs
The Serokell references now point to the NixOS org. I also removed the maintainer field from the cabalfile since there isn't a single maintainer.
> Remove leftover license/author mentions and fix more Serokell references

- .github/workflows/main.yml
- scripts/sync-pr.sh
Implements #163 (see for more context) by reusing the script [from before](https://github.com/piegamesde/nixfmt/pull/1). I took the time to clean up the script to a reasonable degree now though :)
For now it won't work for PRs from forks, but in turn it should work for this PR itself, let's see..
> Automated Nixpkgs diffs for PRs

- .github/workflows/main.yml
- default.nix
- main/Main.hs
- main/System/IO/Utf8.hs
- src/Nixfmt.hs
- src/Nixfmt/Lexer.hs
- src/Nixfmt/Parser.hs
- src/Nixfmt/Parser/Float.hs
- src/Nixfmt/Predoc.hs
- src/Nixfmt/Pretty.hs
- src/Nixfmt/Types.hs
- src/Nixfmt/Util.hs
Enforce [hlint](https://github.com/ndmitchell/hlint) in CI and apply all its suggestions. This just keeps the Haskell code a bit tidier
> Enforce hlint

- .github/workflows/main.yml
A duplicate comment is posted when the action runs the first time, because the posted comment isn't reused.
This could be seen in https://github.com/NixOS/nixfmt/pull/185, and it shouldn't happen in this PR anymore.
> Fix duplicate Nixpkgs diff comment

- .github/workflows/main.yml
- default.nix
- fourmolu.yaml
- main/Main.hs
- main/System/IO/Atomic.hs
- main/System/IO/Utf8.hs
- npins/sources.json
- src/Nixfmt.hs
- src/Nixfmt/Lexer.hs
- src/Nixfmt/Parser.hs
- src/Nixfmt/Parser/Float.hs
- src/Nixfmt/Predoc.hs
- src/Nixfmt/Pretty.hs
- src/Nixfmt/Types.hs
- src/Nixfmt/Util.hs
Ensures that all Nix files are formatted with `pkgs.nixfmt-rfc-style` (not the local version to avoid having to build the package for the dev environment!) and Haskell files are formatted with [fourmolu](https://fourmolu.github.io/) with some reasonable configuration.
> Ensure formatted Nix and Haskell files

- .github/workflows/main.yml
- .gitignore
- default.nix
- scripts/sync-pr-support.nix
- scripts/sync-pr.sh
- test/test.sh
This is super tricky stuff, but this should allow us to run the Nixpkgs diff for forks without safety issues (e.g. for #193). See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ for some background.
Also included is:
- https://github.com/numtide/treefmt/pull/282
- Some related Nix and CI improvements
Best reviewed commit-by-commit.
---
> Nixpkgs diff for forks

- src/Nixfmt/Pretty.hs
- test/diff/regression-218/in.nix
- test/diff/regression-218/out.nix
> Fix non-idempotent comments in attribute parameters

- scripts/sync-pr-support.nix
Makes sure that when testing formatting on all of Nixpkgs, the AST doesn't change, important for https://github.com/NixOS/nixpkgs/issues/322520
This does make the Nixpkgs diff CI like 1 minute slower per commit, but this seems worth it.
- #219 
- #220 
Also discovered another bug from this, fix: #217
> Use --verify in Nixpkgs diff CI

- src/Nixfmt/Types.hs
This caused an infinite recursion when trying to minimise the non-idempotency when running --verify on
```nix
{
foo
, baz # qux
}:
null
```
---
> Fix infinite recursion when walking Abstractions

- src/Nixfmt/Parser.hs
- src/Nixfmt/Types.hs
- test/diff/operation/in.nix
- test/diff/operation/out.nix
NixOS/nix#11131 landed :tada:
Let the debates about the proper formatting of these particular operators begin! Should they use the same rules as all other operators? This PR assumes yes, but there's an argument for sticking `<|` at the ends of lines rather than at the beginnings, since it is the final value in a chain of `<|`s that is special. :shrug:
> Support pipe operators

- MAINTENANCE.md
- main/Main.hs
- nixfmt.cabal
https://github.com/NixOS/nixfmt/issues/229
> Allow overwriting the version with a .version file

- nixfmt.cabal
Hi there! Wanted to build nixfmt using the latest GHC (`brew install cabal-install`) and had to loosen the base version requirement to make it build
> Allow building with newest GHC

- src/Nixfmt/Lexer.hs
- src/Nixfmt/Types.hs
- benchmarks on maintainer-list.nix give a baseline of 88M max residency, nice triangle of death and a bit over 4 seconds duration
- heap profile shows a lot of memory allocated to (,)
- removing usagge of (,) in own code didn't affect the profile
- changing to strict state improves memory from 88 to 40 max residency and runtime goes down by 1 second
> [fix] remove space leaks in (,) by using strict state

- scripts/sync-pr.sh
Previously the Nixpkgs diff script would first format the latest base branch commit, before formatting with each of the PRs commits. This however causes problems if the PR commits are on top of a much older commit that has bugs that aren't in the base branch anymore.
More visually, a PR branch graph looks like this:
```mermaid
gitGraph
commit id:"B"
branch pr
checkout pr
commit id:"P"
commit id:"Q"
checkout main
commit id:"L"
```
Where
- B: Earlier commit on the base branch off of which the PR is branched off (aka merge base)
- L: Latest commit on the base branch, fixes a bug
- P: First commit of the PR, doesn't contain the bug fix
- Q: Second commit of the PR, also doesn't contain the bug fix
Previously CI ran:
- Format with L, with bugfix
- Format with P, without bugfix
- Format with Q, …
> Run Nixpkgs diff on nixfmt commits merged into the base branch

- src/Nixfmt/Pretty.hs
- test/correct/regression-207.nix
Try to fix https://github.com/NixOS/nixfmt/issues/207
---
> Fix selections getting expanded too liberally

- main/Main.hs
- nixfmt.cabal
The recursive mode has caused problems because it doesn't do any filtering, which can mess with files in `.git` directories and elsewhere. While we could support sane implicit filters and an interface to filter explicitly, that adds complexity and maintenance burden.
Instead, we can promote the use of `treefmt` instead, a "formatting multiplexer", which supports file filtering by default. So `nixfmt` will only be the "backend" formatter, while `treefmt` is the frontend.
Previously discussed in a team meeting here:
https://github.com/NixOS/nixfmt/issues/151#issuecomment-2008026386
> Deprecate recursive mode

- main/System/IO/Atomic.hs
Fixes https://github.com/NixOS/nixfmt/issues/73
```
$ cabal install --installdir=$PWD/bin
Wrote tarball sdist to
/home/tweagysil/src/nixfmt/dist-newstyle/sdist/nixfmt-0.6.0.tar.gz
Resolving dependencies...
Symlinking 'nixfmt' to '/home/tweagysil/src/nixfmt/bin/nixfmt'
$ echo '1  +  1' > a.nix
$ sudo chown root:root a.nix
$ bin/nixfmt a.nix
nixfmt: ./.a.nix357406-0.atomic: setOwnerAndGroup: permission denied (Operation not permitted)
$ cat a.nix
1  +  1
$ stat -c "%U:%G" a.nix
root:root
$ sudo bin/nixfmt a.nix
$ cat a.nix
1 + 1
$ stat -c "%U:%G" a.nix
root:root
```
---
> Maintain same ownership when formatting

- src/Nixfmt/Pretty.hs
- src/Nixfmt/Types.hs
- test/diff/apply/in.nix
- test/diff/apply/out-pure.nix
- test/diff/apply/out.nix
- test/diff/idioms_lib_3/out-pure.nix
- test/diff/idioms_lib_3/out.nix
- test/diff/idioms_lib_4/out-pure.nix
- test/diff/idioms_lib_4/out.nix
- test/diff/idioms_nixos_1/out-pure.nix
- test/diff/idioms_nixos_1/out.nix
- test/diff/idioms_nixos_2/out-pure.nix
- test/diff/idioms_nixos_2/out.nix
This is just a quick experiment to see where we can go with this.
> Don't expand lists within functions

- src/Nixfmt/Types.hs
Should fix #261, but I can't easily test it, so I'd appreciate if @symphorien could try this :)
---
> Ensure 64-bit integers don't get trimmed on 32bit platforms

- main/Main.hs
When `--filename path` is specified, any diagnostics will use the `path` instead of `<stdin>`.
Closes #263
> Add `--filename` flag for overriding the filename when using stdioTarget

- src/Nixfmt/Parser.hs
- src/Nixfmt/Pretty.hs
- src/Nixfmt/Util.hs
- test/diff/apply_with_lists/in.nix
- test/diff/apply_with_lists/out-pure.nix
- test/diff/apply_with_lists/out.nix
- test/diff/attr_set/in.nix
- test/diff/attr_set/out-pure.nix
- test/diff/attr_set/out.nix
- test/diff/idioms_nixos_2/out-pure.nix
- test/diff/idioms_nixos_2/out.nix
- test/diff/string_interpol/out-pure.nix
- test/diff/string_interpol/out.nix
Picking some low hanging fixes before the big treewide
> Final polish

- .github/workflows/main.yml
This restricts the action to be no longer able to push content, so it can only comment on PRs or open and close (not merge) them.
This means that even if someone manages to bypass the sandboxing somehow, they can not really exploit this workflow to extract secrets etc.
> Improve sandboxing of `pull_request_target` workflow

- main/Main.hs
- src/Nixfmt/Predoc.hs
- test/correct-indent-4.nix
- test/test.sh
Makes it easier to override or, hopefully in the future, make configurable (weird you can configure the line length, but not indentation width).
Personally I find 2-space-indented code very difficult to read. I am maintaining a fork on Codeberg to help myself in my own code bases with this patch (but increased indentation width) but this means anyone that wants to also change the indentation only needs to patch a single line instead of multiple spots.  This could be fixed if Nix were to support tabs, but that isn’t the case. It also just seems better practice to define the indentation than `2` integers thru the code.
[^1]
[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free …
> Make indentation configurable

- README.md
- default.nix
- main/Main.hs
- nixfmt.cabal
- test/mergetool.sh
Inspired by @oxij's https://github.com/NixOS/nixfmt/pull/277, but implemented in Haskell, therefore faster (less process spawning) and trivially integrated into the build and distribution.
Things done:
---
This work is funded by [Antithesis](https://antithesis.com/) and [Tweag](https://tweag.io) :sparkles:
> Implement --mergetool mode

- main/Main.hs
Depends on it being introduced with https://github.com/NixOS/nixpkgs/pull/384857 first. This will make it much easier to discover.
---
This work is funded by [Antithesis](https://antithesis.com/) and [Tweag](https://tweag.io) :sparkles:
> Mention pkgs.nixfmt-tree in directory deprecation warning

- README.md
it's not clear for first-time readers which `nixfmt` the first sentence
referred to, since the repo has switched owners
> reword introduction for clarity

- src/Nixfmt/Parser.hs
- src/Nixfmt/Pretty.hs
- src/Nixfmt/Types.hs
- standard.md
- test/diff/attr_set/in.nix
- test/diff/attr_set/out-pure.nix
- test/diff/attr_set/out.nix
- test/diff/idioms_nixos_1/out-pure.nix
- test/diff/idioms_nixos_1/out.nix
- test/diff/idioms_nixos_2/out-pure.nix
- test/diff/idioms_nixos_2/out.nix
- test/diff/idioms_pkgs_3/out-pure.nix
- test/diff/idioms_pkgs_3/out.nix
- test/diff/idioms_pkgs_4/out-pure.nix
- test/diff/idioms_pkgs_4/out.nix
- test/diff/idioms_pkgs_5/out-pure.nix
- test/diff/idioms_pkgs_5/out.nix
Quick experiment for #228 #284. Honestly I'm more "vibe coding" than anything else here, this issue is stretching our engine past its limits, and properly reasoning about what which knobs to turn is really expensive on brainpower
Closes #228, Closes #309
> Tweak operation absorbtion (ex. Unindent Concatenation)

- .pre-commit-hooks.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- MAINTENANCE.md
- README.md
- nixfmt.cabal
> Release 1.0.0

- src/Nixfmt.hs
Send --ir output to stderr, like --ast, to prevent overwriting source files with IR. Closes #313
> [#313] Send output of --ir to stderr

- src/Nixfmt/Lexer.hs
- src/Nixfmt/Pretty.hs
- src/Nixfmt/Types.hs
- standard.md
- test/diff/language-annotation/in.nix
- test/diff/language-annotation/out-pure.nix
- test/diff/language-annotation/out.nix
- test/diff/monsters_4/out-pure.nix
- test/diff/monsters_4/out.nix
- test/diff/string_interpol/out-pure.nix
- test/diff/string_interpol/out.nix
Initial work to get language annotation support working
This pr is not ready, but I created it mostly to get feedback on how we should handle edge cases and the direction I'm taking.
closes #179
> Language annotation support

- CHANGELOG.md
- nixfmt.cabal
- Added support for "language annotation" comments (e.g. `/* lang */ ""`), used by things like tree-sitter grammars: <https://github.com/NixOS/nixfmt/pull/343>
- Fixed a regression causing incorrect path value indentation: <https://github.com/NixOS/nixfmt/pull/342>
Commits since 1.0.1: https://github.com/NixOS/nixfmt/compare/v1.0.1...master
> Release 1.1.0
